# Generated by Django 4.1.7 on 2023-03-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='other_names',
            new_name='other_name',
        ),
    ]
