# Generated by Django 4.1.7 on 2023-03-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_other_names_member_other_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='surname',
        ),
        migrations.AddField(
            model_name='member',
            name='Date_of_birth',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='District',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='Missional_Community',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='Place_of_residence',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='Primary_phone_number',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='Profession',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='Whatsapp_phone_number',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='Other_name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='Surname',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
