# Generated by Django 4.1.7 on 2023-03-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_other_name_remove_member_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Date_of_birth',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
    ]
