# Generated by Django 4.1.7 on 2023-03-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Date_of_birth',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
