# Generated by Django 4.1.7 on 2023-04-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='District',
            new_name='Work_place',
        ),
    ]
