# Generated by Django 4.1.7 on 2023-04-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_rename_district_member_work_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Profession',
        ),
    ]
