# Generated by Django 4.1.7 on 2023-04-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_rename_primary_phone_number_member_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Date_of_birth',
            field=models.DateField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='Wedding_anniversary',
            field=models.DateField(default='None', max_length=50),
        ),
    ]
